### PR TITLE
Realm name in routing key

### PR DESCRIPTION
**Pull request by marciprete**
Currently, the routing key shows a UUID where is supposed to be the realm name.
I've modified the message producer to retrieve the realm name from the current session

### CODE REVIEW

**Comment by aznamier** [comment]
@marciprete 

Thanks, What version of Keycloak is giving UUID for the routing key?

I have just checked this plugin with 15 and 22, and I get real realm name in the routing key. So cannot replicate the issue.

**Comment by mortifactor** [comment]
Hello. I have the same problem. E.g. I've created the binding "KK.EVENT.#" and have created new user through the admin console. Then the "routing key" in received message in queue is:

```
KK.EVENT.ADMIN.05a6d9a8-4d1f-41a8-b87d-8363944fe9b2.SUCCESS.USER.CREATE
```
so it is the realm id instead of name

**Comment by gilamarko** [comment]
Also tested with keycloak 22.0.3 same behavior, needs the realmId (UUID)

**Comment by marciprete** [comment]
Hello,
I had this issue on Keycloak 16.0.1 and 19.0.3.

**Comment by marciprete** [comment]
> Also tested with keycloak 22.0.3 same behavior, needs the realmId (UUID)

@gilamarko if you wish, you can test my revision from branch /feature/realm-name-instead-of-uuid

**Comment by aznamier** [comment]
@marciprete Thank you for that contribution

**Comment by gilamarko** [comment]
> > Also tested with keycloak 22.0.3 same behavior, needs the realmId (UUID)
> 
> @gilamarko if you wish, you can test my revision from branch /feature/realm-name-instead-of-uuid

Works as expected.

**Comment by huyqnguyen-it** [comment]
use this to get realm name 
`		String realmName = session.getContext().getRealm().getName();
` #52

**Pull request merged**
